const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={items:[],comic:null,original:[],working:[],page:0,filter:{author:"",group:""},dragIndex:null};
const api=async(url,options={})=>{const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options});if(!r.ok){let e;try{e=await r.json()}catch{e={detail:r.statusText}}throw new Error(e.detail||"操作失敗")}return r.json()};
const fmt=n=>{if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";if(n<1073741824)return(n/1048576).toFixed(1)+" MB";return(n/1073741824).toFixed(1)+" GB"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className="toast show"+(error?" error":"");setTimeout(()=>el.className="toast",3200)}
function imageUrl(id,name){return `/api/comics/${id}/image?name=${encodeURIComponent(name)}`}
async function loadRoots(){const roots=await api("/api/roots");$("#roots").innerHTML=roots.length?roots.map(r=>`<div>${esc(r.path)}</div>`).join(""):"尚未設定"}
async function loadLibrary(){const q=new URLSearchParams({q:$("#search").value,sort:$("#sort").value,author:state.filter.author,group:state.filter.group});const data=await api("/api/comics?"+q);state.items=data.items;$("#summary").textContent=`${data.items.length} 個檔案${state.filter.author?` · 作者：${state.filter.author}`:""}${state.filter.group?` · 分組：${state.filter.group}`:""}`;renderNav("authors",data.authors,"author");renderNav("groups",data.groups,"group");renderCards()}
function renderNav(id,values,type){$("#"+id).innerHTML=values.map(v=>`<button class="${state.filter[type]===v?"active":""}" data-filter="${type}" data-value="${esc(v)}"><span>${esc(v)}</span></button>`).join("")}
function renderCards(){const lib=$("#library");$("#empty").classList.toggle("hidden",state.items.length>0);lib.innerHTML=state.items.map(c=>`<article class="card" data-id="${c.id}"><div class="cover">${c.cover_name?`<img loading="lazy" src="${imageUrl(c.id,c.cover_name)}">`:""}<span class="format">${esc(c.extension.slice(1).toUpperCase())}</span><span class="pages">${c.image_count} 頁</span></div><div class="card-body"><h3 title="${esc(c.name)}">${esc(c.name)}</h3><div class="meta">${c.author?`<span class="tag">${esc(c.author)}</span>`:""}${c.group_name?`<span class="tag">${esc(c.group_name)}</span>`:""}<span>${fmt(c.size_bytes)}</span></div><div class="card-path" title="${esc(c.path)}">${esc(c.path)}</div></div></article>`).join("")}
async function showDetail(id){const c=await api(`/api/comics/${id}`);state.comic=c;$("#detailBody").innerHTML=`<div class="detail-grid"><img class="detail-cover" src="${c.cover_name?imageUrl(c.id,c.cover_name):""}"><div class="detail-info"><p class="eyebrow">${esc(c.extension.slice(1).toUpperCase())} · ${c.image_count} 頁</p><h2>${esc(c.name)}</h2><dl><dt>推測作品</dt><dd>${esc(c.title_guess||"—")}</dd><dt>集數</dt><dd>${esc(c.volume_guess||"—")}</dd><dt>大小</dt><dd>${fmt(c.size_bytes)}</dd><dt>完整路徑</dt><dd>${esc(c.path)}</dd>${c.error?`<dt>錯誤</dt><dd>${esc(c.error)}</dd>`:""}</dl><div class="detail-fields"><label>作者<input id="authorInput" value="${esc(c.author)}" placeholder="可留空"></label><label>自訂分組<input id="groupInput" value="${esc(c.group_name)}" placeholder="可留空"></label></div><div class="detail-actions"><button class="primary" id="readComic">開始閱讀</button><button class="ghost" id="saveMetadata">儲存分類</button><button class="ghost" id="openFolder">開啟所在資料夾</button><button class="ghost" id="renameFile">重新命名</button><button class="ghost" id="moveFile">移動</button><button class="danger" id="deleteFile">刪除</button></div></div></div>`;$("#detailDialog").showModal()}
async function saveMetadata(){await api(`/api/comics/${state.comic.id}/metadata`,{method:"PATCH",body:JSON.stringify({author:$("#authorInput").value,group_name:$("#groupInput").value})});toast("分類已儲存，原始檔案未變更");$("#detailDialog").close();loadLibrary()}
async function startReader(){const c=await api(`/api/comics/${state.comic.id}`);state.comic=c;state.original=c.images.map(x=>({source:x.name,name:x.name,deleted:false}));state.working=structuredClone(state.original);state.page=0;$("#detailDialog").close();$("#reader").classList.remove("hidden");$("#reader").focus();renderPage()}
function visibleItems(){return state.working.filter(x=>!x.deleted)}
function changes(){let moved=0,renamed=0,deleted=0;state.working.forEach((x,i)=>{const old=state.original.find(y=>y.source===x.source);if(x.deleted)deleted++;else{if(x.name!==old.name)renamed++;const oldVisible=state.original.filter(y=>!y.deleted).findIndex(y=>y.source===x.source);if(oldVisible!==visibleItems().findIndex(y=>y.source===x.source))moved++}});return{moved,renamed,deleted,total:moved+renamed+deleted}}
function renderPage(){const list=visibleItems();if(!list.length){toast("沒有可閱讀圖片",true);return}state.page=Math.max(0,Math.min(state.page,list.length-1));const item=list[state.page];$("#readerTitle").textContent=state.comic.title_guess||state.comic.name;$("#readerFile").textContent=state.comic.name;$("#pageImage").src=imageUrl(state.comic.id,item.source);$("#pageCounter").textContent=`${state.page+1} / ${list.length}`;$("#pageName").textContent=item.name;const c=changes();$("#dirtyBadge").classList.toggle("hidden",!c.total);$("#dirtyBadge").textContent=`尚未儲存：${c.total} 項變更`;renderThumbs()}
function movePage(delta){state.page+=delta;renderPage()}
function renderThumbs(){const list=visibleItems();$("#thumbStrip").innerHTML=list.map((x,i)=>`<img class="${i===state.page?"active":""}" data-page="${i}" loading="lazy" src="${imageUrl(state.comic.id,x.source)}" title="${esc(x.name)}">`).join("")}
function openEditor(){const current=visibleItems()[state.page];$("#reader").classList.add("hidden");$("#editor").classList.remove("hidden");renderEditor();requestAnimationFrame(()=>document.querySelector(`[data-source="${CSS.escape(current.source)}"]`)?.scrollIntoView({block:"center"}))}
function renderEditor(){const c=changes();$("#editSummary").textContent=c.total?`尚未儲存：移動 ${c.moved}、改名 ${c.renamed}、刪除 ${c.deleted}`:"目前沒有變更";$("#editGrid").innerHTML=state.working.map((x,i)=>`<article draggable="true" class="edit-item ${x.deleted?"deleted":""}" data-index="${i}" data-source="${esc(x.source)}"><span class="number">${i+1}</span><img loading="lazy" src="${imageUrl(state.comic.id,x.source)}"><div class="item-info"><div class="item-name" title="${esc(x.name)}">${esc(x.name)}</div><div class="item-actions"><button data-action="rename">改名</button><button data-action="delete">${x.deleted?"復原":"刪除"}</button><button data-action="first">移到最前</button></div></div></article>`).join("")}
function returnReader(){const current=state.working.find(x=>!x.deleted);state.page=Math.max(0,visibleItems().findIndex(x=>x.source===current?.source));$("#editor").classList.add("hidden");$("#reader").classList.remove("hidden");renderPage()}
function prepareApply(){const c=changes();if(!c.total)return toast("目前沒有需要套用的變更");$("#confirmSummary").innerHTML=`<strong>${esc(state.comic.name)}</strong><br>${esc(state.comic.path)}<br><br>保留圖片：${visibleItems().length}<br>順序變更：${c.moved}<br>刪除：${c.deleted}<br>重新命名：${c.renamed}`;$("#confirmText").value="";$("#confirmDialog").showModal()}
async function applyChanges(e){e.preventDefault();if($("#confirmText").value!=="套用並覆蓋")return toast("確認文字不正確",true);$("#confirmApply").disabled=true;try{await api(`/api/comics/${state.comic.id}/apply`,{method:"POST",body:JSON.stringify({items:state.working,confirmation:"套用並覆蓋"})});$("#confirmDialog").close();$("#editor").classList.add("hidden");toast("新檔已驗證並完成覆蓋");await loadLibrary()}catch(e){toast(e.message,true)}finally{$("#confirmApply").disabled=false}}
async function fileAction(kind){const c=state.comic;let value="";if(kind==="rename"){value=prompt("輸入新檔名",c.name);if(!value)return}else if(kind==="move"){value=prompt("輸入目的資料夾的完整路徑",c.path.substring(0,c.path.lastIndexOf("\\")));if(!value)return}const confirmation=prompt(`這會實際${kind==="delete"?"刪除":kind==="move"?"移動":"重新命名"}檔案。\n請輸入目前完整檔名確認：\n${c.name}`);if(confirmation===null)return;await api(`/api/comics/${c.id}/${kind}`,{method:"POST",body:JSON.stringify({value,confirmation})});$("#detailDialog").close();toast("檔案操作已完成");loadLibrary()}
let searchTimer;$("#search").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadLibrary,250)});$("#sort").addEventListener("change",loadLibrary);$("#library").addEventListener("click",e=>{const card=e.target.closest(".card");if(card)showDetail(card.dataset.id)});document.addEventListener("click",e=>{const f=e.target.closest("[data-filter]");if(f){state.filter={author:"",group:""};state.filter[f.dataset.filter]=f.dataset.value;loadLibrary()}const close=e.target.closest("[data-close]");if(close)document.getElementById(close.dataset.close).close()});
$("#clearFilter").onclick=()=>{state.filter={author:"",group:""};$("#search").value="";loadLibrary()};$("#addRoot").onclick=async()=>{const b=$("#addRoot");b.disabled=true;b.textContent="請在視窗中選擇…";try{const picked=await api("/api/pick-folder",{method:"POST",body:"{}"});if(!picked.selected)return;await api("/api/roots",{method:"POST",body:JSON.stringify({path:picked.path})});await loadRoots();toast("掃描位置已加入，按「重新掃描書庫」開始索引")}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent="＋ 新增掃描資料夾"}};$("#scan").onclick=async()=>{const b=$("#scan");b.disabled=true;b.textContent="掃描中…";try{const r=await api("/api/scan",{method:"POST",body:"{}"});toast(`掃描完成：找到 ${r.found}、更新 ${r.updated}、失敗 ${r.failed}`);await loadLibrary()}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent="↻ 重新掃描書庫"}};
$("#detailBody").addEventListener("click",async e=>{try{if(e.target.id==="saveMetadata")saveMetadata();if(e.target.id==="readComic")startReader();if(e.target.id==="openFolder")await api(`/api/comics/${state.comic.id}/open-folder`,{method:"POST"});if(e.target.id==="renameFile")fileAction("rename");if(e.target.id==="moveFile")fileAction("move");if(e.target.id==="deleteFile")fileAction("delete")}catch(err){toast(err.message,true)}});$("#closeReader").onclick=()=>{$("#reader").classList.add("hidden");loadLibrary()};$("#previous").onclick=()=>movePage(-1);$("#next").onclick=()=>movePage(1);$("#pageImage").onclick=e=>e.target.classList.toggle("zoom");$("#toggleThumbs").onclick=()=>$("#thumbStrip").classList.toggle("hidden");$("#thumbStrip").onclick=e=>{if(e.target.dataset.page){state.page=+e.target.dataset.page;renderPage()}};$("#editOrder").onclick=openEditor;document.addEventListener("keydown",e=>{if(!$("#reader").classList.contains("hidden")){if(e.key==="ArrowLeft")movePage(-1);if(e.key==="ArrowRight")movePage(1);if(e.key==="Escape")$("#reader").classList.add("hidden")}});
$("#editGrid").addEventListener("dragstart",e=>{const item=e.target.closest(".edit-item");if(!item)return;state.dragIndex=+item.dataset.index;item.classList.add("dragging")});$("#editGrid").addEventListener("dragend",e=>e.target.closest(".edit-item")?.classList.remove("dragging"));$("#editGrid").addEventListener("dragover",e=>e.preventDefault());$("#editGrid").addEventListener("drop",e=>{e.preventDefault();const target=e.target.closest(".edit-item");if(!target)return;const to=+target.dataset.index;const [item]=state.working.splice(state.dragIndex,1);state.working.splice(to,0,item);renderEditor()});$("#editGrid").addEventListener("click",e=>{const item=e.target.closest(".edit-item");const action=e.target.dataset.action;if(!item||!action)return;const i=+item.dataset.index,x=state.working[i];if(action==="rename"){const name=prompt("圖片的新名稱（含副檔名）",x.name);if(name)x.name=name}if(action==="delete")x.deleted=!x.deleted;if(action==="first"){state.working.splice(i,1);state.working.unshift(x)}renderEditor()});$("#discard").onclick=()=>{if(confirm("放棄所有尚未儲存的修改？")){state.working=structuredClone(state.original);renderEditor()}};$("#returnReader").onclick=returnReader;$("#apply").onclick=prepareApply;$("#confirmApply").onclick=applyChanges;$("#hashDuplicates").onclick=async()=>{if(!confirm("只會對檔案大小相同的候選檔計算 SHA-256，不會刪除任何檔案。要開始嗎？"))return;try{const r=await api("/api/duplicates/hash",{method:"POST"});toast(`完成：計算 ${r.calculated} 個檔案，找到 ${r.groups.length} 組完全重複`)}catch(e){toast(e.message,true)}};
Promise.all([loadRoots(),loadLibrary()]).catch(e=>toast(e.message,true));
